version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: '17:00'
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: browser
    versions:
    - ">= 4.a, < 5"
  - dependency-name: factory_bot_rails
    versions:
    - ">= 5.a, < 6"
  - dependency-name: raygun4ruby
    versions:
    - ">= 3.a, < 4"
  - dependency-name: rubocop
    versions:
    - ">= 0.62.a, < 0.63"
  - dependency-name: rubocop
    versions:
    - ">= 0.63.a, < 0.64"
