version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "17:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: puppeteer
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "17:00"
    open-pull-requests-limit: 10
