engines:
  # https://docs.codeclimate.com/docs/eslint
  eslint:
    enabled: false
  rubocop:
    enabled: true
    channel: rubocop-0-93
  sass-lint:
    enabled: true
  shellcheck:
    enabled: true
  brakeman:
    enabled: false
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.js"
  - "**.coffee"
  - "**.sass"
  - "**.haml"
  - "**.css"
  - "**.scss"
  - Gemfile.lock
exclude_paths:
- config/
- db/
- spec/
- bin/
- vendor/
