engines:
  eslint:
    enabled: true
    checks:
      no-var:
        enabled: false
      require-jsdoc:
        enabled: false
  rubocop:
    enabled: true
  scss-lint:
    enabled: true
  shellcheck:
    enabled: true
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.js"
  - "**.coffee"
  - "**.sass"
  - "**.haml"
  - "**.css"
  - "**.scss"
  - Gemfile.lock
exclude_paths:
- config/
- db/
- spec/
- bin/
