# Built-in config:
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'

Layout/LineLength:
  Max: 130

Lint/Void:
  Enabled: false # see spec/controllers/vocab_sheet_controller_spec.rb

Metrics/AbcSize:
  Max: 26

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'config/**/*.rb'

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/PerceivedComplexity:
  Max: 12

Naming/VariableNumber:
  EnforcedStyle: snake_case

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/Sum:
  Enabled: true

Performance/UnfreezeString:
  Enabled: false

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/AfterCommitOverride:
  Enabled: true

Rails/FilePath:
  EnforcedStyle: arguments

Rails/FindById:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/SquishedSQLHeredocs:
  Enabled: true

Rails/WhereExists:
  Enabled: true

Rails/WhereNot:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

# Just always use double quotes and stop thinking about it.
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
