# Built-in config:
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml

require:
  - rubocop-rails
  - rubocop-performance


Style/AccessorGrouping:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Lint/Void:
  Enabled: false # see spec/controllers/vocab_sheet_controller_spec.rb

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 130

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 22

Metrics/PerceivedComplexity:
  Max: 12

Rails/FilePath:
  EnforcedStyle: arguments

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Performance/UnfreezeString:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'config/**/*.rb'

Style/PercentLiteralDelimiters:
  Enabled: false

Naming/FileName:
  Exclude:
    - Gemfile
    - Gemfile.lock

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_lint.html#lintmixedregexpcapturetypes
Lint/MixedRegexpCaptureTypes:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#styleredundantregexpcharacterclass
Style/RedundantRegexpCharacterClass:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#styleredundantregexpescape
Style/RedundantRegexpEscape:
  Enabled: true

