# Built-in config:
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml

require: rubocop-performance

Lint/Void:
  Enabled: false # see spec/controllers/vocab_sheet_controller_spec.rb

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'config/**/*.rb'

Style/PercentLiteralDelimiters:
  Enabled: false

Naming/FileName:
  Exclude:
    - Gemfile
    - Gemfile.lock

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
