# https://github.com/sasstools/sass-lint
files:
  include: 'app/assets/stylesheets/**/*.s+(a|c)ss'
rules:
  class-name-format:
    - 1
    - convention: strictbem
  nesting-depth:
    - 1
    - max-depth: 3
  leading-zero:
    - 1
    - include: true

  # This app has a lot of existing SCSS which uses extend with real classes.
  placeholder-in-extend:
    - 0
  force-pseudo-nesting:
    - 0
  shorthand-values:
    - 1
    -
      allowed-shorthands:
        - 1
        - 2

