require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PagePartsController do

  def mock_page_part(stubs={})
    @mock_page_part ||= mock_model(PagePart, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all page_parts as @page_parts" do
      PagePart.stub(:all) { [mock_page_part] }
      get :index
      assigns(:page_parts).should eq([mock_page_part])
    end
  end

  describe "GET show" do
    it "assigns the requested page_part as @page_part" do
      PagePart.stub(:find).with("37") { mock_page_part }
      get :show, :id => "37"
      assigns(:page_part).should be(mock_page_part)
    end
  end

  describe "GET new" do
    it "assigns a new page_part as @page_part" do
      PagePart.stub(:new) { mock_page_part }
      get :new
      assigns(:page_part).should be(mock_page_part)
    end
  end

  describe "GET edit" do
    it "assigns the requested page_part as @page_part" do
      PagePart.stub(:find).with("37") { mock_page_part }
      get :edit, :id => "37"
      assigns(:page_part).should be(mock_page_part)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created page_part as @page_part" do
        PagePart.stub(:new).with({'these' => 'params'}) { mock_page_part(:save => true) }
        post :create, :page_part => {'these' => 'params'}
        assigns(:page_part).should be(mock_page_part)
      end

      it "redirects to the created page_part" do
        PagePart.stub(:new) { mock_page_part(:save => true) }
        post :create, :page_part => {}
        response.should redirect_to(page_part_url(mock_page_part))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved page_part as @page_part" do
        PagePart.stub(:new).with({'these' => 'params'}) { mock_page_part(:save => false) }
        post :create, :page_part => {'these' => 'params'}
        assigns(:page_part).should be(mock_page_part)
      end

      it "re-renders the 'new' template" do
        PagePart.stub(:new) { mock_page_part(:save => false) }
        post :create, :page_part => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested page_part" do
        PagePart.stub(:find).with("37") { mock_page_part }
        mock_page_part.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :page_part => {'these' => 'params'}
      end

      it "assigns the requested page_part as @page_part" do
        PagePart.stub(:find) { mock_page_part(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:page_part).should be(mock_page_part)
      end

      it "redirects to the page_part" do
        PagePart.stub(:find) { mock_page_part(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(page_part_url(mock_page_part))
      end
    end

    describe "with invalid params" do
      it "assigns the page_part as @page_part" do
        PagePart.stub(:find) { mock_page_part(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:page_part).should be(mock_page_part)
      end

      it "re-renders the 'edit' template" do
        PagePart.stub(:find) { mock_page_part(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested page_part" do
      PagePart.stub(:find).with("37") { mock_page_part }
      mock_page_part.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the page_parts list" do
      PagePart.stub(:find) { mock_page_part }
      delete :destroy, :id => "1"
      response.should redirect_to(page_parts_url)
    end
  end

end
