name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          # Note: This service fails its docker health check unless you specify these environment variables
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nzsl_test
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        # this action will install whatever ruby is given in .ruby-version file

      - name: Install NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install required JS packages
        run: |
          yarn install

      - name: Setup CodeClimate Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Prepare app for testing
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/test
          RAILS_ENV: test
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails db:prepare

      - name: Run JS linting
        run: |
          npm run eslint

      - name: Run Ruby static analysis
        run: |
          gem install --no-document brakeman
          brakeman --run-all-checks --exit-on-warn --format plain .

      - name: Run Ruby linting
        run: |
          bundle exec rubocop -D

      - name: Run ruby specs
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/test
          PERCY_TARGET_BRANCH: staging
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: |
          npx percy exec -- bundle exec rspec spec

